// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	asset "github.com/adesupraptolaia/assetfindr/service/asset"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateNewAsset provides a mock function with given fields: ctx, data
func (_m *Service) CreateNewAsset(ctx context.Context, data asset.Asset) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, asset.Asset) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAsset provides a mock function with given fields: ctx, ID
func (_m *Service) DeleteAsset(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllAssets provides a mock function with given fields: ctx
func (_m *Service) GetAllAssets(ctx context.Context) ([]asset.Asset, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssets")
	}

	var r0 []asset.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]asset.Asset, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []asset.Asset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]asset.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAssetByID provides a mock function with given fields: ctx, ID
func (_m *Service) GetAssetByID(ctx context.Context, ID string) (*asset.Asset, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetByID")
	}

	var r0 *asset.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*asset.Asset, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *asset.Asset); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*asset.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAsset provides a mock function with given fields: ctx, ID, data
func (_m *Service) UpdateAsset(ctx context.Context, ID string, data asset.Asset) error {
	ret := _m.Called(ctx, ID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, asset.Asset) error); ok {
		r0 = rf(ctx, ID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
